<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="103511" started-at="2018-03-01T22:49:19Z" finished-at="2018-03-01T22:51:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="103511" started-at="2018-03-01T22:49:19Z" finished-at="2018-03-01T22:51:02Z">
      <class name="net.ed.YahooFinanceScraper_Test">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:net.ed.YahooFinanceScraper_Test@757942a1]" name="launchBrowser" is-config="true" duration-ms="2106" started-at="2018-03-01T22:49:19Z" finished-at="2018-03-01T22:49:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="getURL_Test()[pri:1, instance:net.ed.YahooFinanceScraper_Test@757942a1]" name="getURL_Test" duration-ms="11304" started-at="2018-03-01T22:49:21Z" finished-at="2018-03-01T22:49:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getURL_Test -->
        <test-method status="PASS" signature="getCookies_Test()[pri:2, instance:net.ed.YahooFinanceScraper_Test@757942a1]" name="getCookies_Test" duration-ms="75856" started-at="2018-03-01T22:49:32Z" finished-at="2018-03-01T22:50:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCookies_Test -->
        <test-method status="FAIL" signature="getPortfolioURL_Test()[pri:3, instance:net.ed.YahooFinanceScraper_Test@757942a1]" name="getPortfolioURL_Test" duration-ms="2103" started-at="2018-03-01T22:50:48Z" finished-at="2018-03-01T22:50:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Watchlist - Yahoo Finance Portfolios] but found [Yahoo Finance - Business Finance, Stock Market, Quotes, News]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Watchlist - Yahoo Finance Portfolios] but found [Yahoo Finance - Business Finance, Stock Market, Quotes, News]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at net.ed.YahooFinanceScraper_Test.getPortfolioURL_Test(YahooFinanceScraper_Test.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPortfolioURL_Test -->
        <test-method status="PASS" signature="scrapeMyTotals_Test()[pri:4, instance:net.ed.YahooFinanceScraper_Test@757942a1]" name="scrapeMyTotals_Test" duration-ms="2210" started-at="2018-03-01T22:50:50Z" finished-at="2018-03-01T22:50:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- scrapeMyTotals_Test -->
        <test-method status="FAIL" signature="scrapeMyData_Test()[pri:5, instance:net.ed.YahooFinanceScraper_Test@757942a1]" name="scrapeMyData_Test" duration-ms="879" started-at="2018-03-01T22:50:53Z" finished-at="2018-03-01T22:50:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Watchlist - Yahoo Finance Portfolios] but found [Yahoo Finance - Business Finance, Stock Market, Quotes, News]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Watchlist - Yahoo Finance Portfolios] but found [Yahoo Finance - Business Finance, Stock Market, Quotes, News]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at net.ed.YahooFinanceScraper_Test.scrapeMyData_Test(YahooFinanceScraper_Test.java:171)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- scrapeMyData_Test -->
        <test-method status="PASS" signature="terminateBrowser()[pri:0, instance:net.ed.YahooFinanceScraper_Test@757942a1]" name="terminateBrowser" is-config="true" duration-ms="9006" started-at="2018-03-01T22:50:53Z" finished-at="2018-03-01T22:51:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateBrowser -->
      </class> <!-- net.ed.YahooFinanceScraper_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
